server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/minigfs
spring.datasource.username=minigfs
spring.datasource.password=minigfs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
