server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/minigfs
spring.datasource.username=minigfs
spring.datasource.password=minigfs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

minigfs.chunk-size=1048576
minigfs.replication-factor=2

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
