version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: mini-gfs-postgres
    environment:
      POSTGRES_DB: minigfs
      POSTGRES_USER: minigfs
      POSTGRES_PASSWORD: minigfs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: